#!/usr/bin/env node
/**
 * vendor-ui.mjs — pre-build step for `@flux/plugin-sdk`.
 *
 * Copies the host's shadcn primitives + `cn` helper into the SDK's
 * source tree under `src/ui-vendored/` so they become part of the
 * published artefact. Without this, npm consumers of the SDK would
 * have to install their own shadcn copies or reach into host-private
 * `@/components/ui/*` aliases that only resolve inside the monorepo.
 *
 * Why a script instead of hand-maintained copies:
 *   • One source of truth (the host's `src/components/ui/*`). Bug
 *     fixes / styling tweaks land in the host and propagate to the
 *     SDK on the next build.
 *   • Zero drift potential: the script always overwrites.
 *   • Comments / imports / variants stay byte-identical, so plugin
 *     authors using the SDK get the same visual + behavioural
 *     contract the host renders.
 *
 * Rewrites performed during copy:
 *   • `from "@/lib/utils"`           → `from "../lib/utils"`
 *   • `from "@/components/ui/foo"`   → `from "./foo"`
 *
 * Everything else is byte-for-byte. The script is idempotent — re-
 * runs produce identical output.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SDK_ROOT = resolve(__dirname, "..");
const REPO_ROOT = resolve(SDK_ROOT, "..", "..");

const HOST_UI_DIR = join(REPO_ROOT, "src", "components", "ui");
const HOST_LIB_DIR = join(REPO_ROOT, "src", "lib");
const VENDOR_UI_DIR = join(SDK_ROOT, "src", "ui-vendored");
const VENDOR_LIB_DIR = join(SDK_ROOT, "src", "lib");

/**
 * Subset of the host's shadcn primitives the SDK exposes. We
 * deliberately do NOT copy every primitive — only the ones plugin
 * authors should rely on. Adding a primitive here means committing
 * to its API stability across SDK majors.
 */
const PRIMITIVES = [
  "button",
  "input",
  "textarea",
  "separator",
  "switch",
  "scroll-area",
  "badge",
  "checkbox",
  "dropdown-menu",
  "tooltip",
  "dialog",
  "select",
  "alert-dialog",
  "context-menu",
  "popover",
];

function rewrite(src) {
  // Drop the leading `"use client"` directive — published consumers
  // bundle the SDK statically and don't need RSC boundaries.
  let s = src.replace(/^"use client";?\s*\n/m, "");
  // `@/lib/utils` → relative to `src/ui-vendored/`.
  s = s.replace(
    /from\s+(['"])@\/lib\/utils\1/g,
    'from "../lib/utils"',
  );
  // `@/components/ui/<file>` → sibling in `src/ui-vendored/`.
  s = s.replace(
    /from\s+(['"])@\/components\/ui\/([^'"]+)\1/g,
    'from "./$2"',
  );
  return s;
}

function copyFile(srcPath, destPath) {
  const body = readFileSync(srcPath, "utf8");
  const rewritten = rewrite(body);
  mkdirSync(dirname(destPath), { recursive: true });
  writeFileSync(destPath, rewritten);
}

function main() {
  mkdirSync(VENDOR_UI_DIR, { recursive: true });
  mkdirSync(VENDOR_LIB_DIR, { recursive: true });

  // Step 1: copy the `cn` helper.
  copyFile(
    join(HOST_LIB_DIR, "utils.ts"),
    join(VENDOR_LIB_DIR, "utils.ts"),
  );

  // Step 2: copy each primitive.
  for (const name of PRIMITIVES) {
    copyFile(
      join(HOST_UI_DIR, `${name}.tsx`),
      join(VENDOR_UI_DIR, `${name}.tsx`),
    );
  }

  // Step 3: write the public barrel that the `./ui` export resolves
  // to. The host re-export list lives in `src/ui.ts`; we mirror its
  // surface here so plugin authors get the same identifier names.
  const barrel = [
    `// Auto-generated by scripts/vendor-ui.mjs — do not edit.`,
    `// Mirrors the export list in src/ui.ts (the workspace alias`,
    `// path) so in-repo plugins and npm consumers see the same`,
    `// public surface from \`@flux/plugin-sdk/ui\`.`,
    ``,
    `export { Button } from "./ui-vendored/button";`,
    `export { Input } from "./ui-vendored/input";`,
    `export { Textarea } from "./ui-vendored/textarea";`,
    `export { Separator } from "./ui-vendored/separator";`,
    `export { Switch } from "./ui-vendored/switch";`,
    `export { ScrollArea } from "./ui-vendored/scroll-area";`,
    `export { Badge } from "./ui-vendored/badge";`,
    `export { Checkbox } from "./ui-vendored/checkbox";`,
    `export {`,
    `  DropdownMenu,`,
    `  DropdownMenuContent,`,
    `  DropdownMenuItem,`,
    `  DropdownMenuLabel,`,
    `  DropdownMenuSeparator,`,
    `  DropdownMenuTrigger,`,
    `} from "./ui-vendored/dropdown-menu";`,
    `export {`,
    `  Tooltip,`,
    `  TooltipContent,`,
    `  TooltipProvider,`,
    `  TooltipTrigger,`,
    `} from "./ui-vendored/tooltip";`,
    `export {`,
    `  Dialog,`,
    `  DialogClose,`,
    `  DialogContent,`,
    `  DialogDescription,`,
    `  DialogFooter,`,
    `  DialogHeader,`,
    `  DialogTitle,`,
    `  DialogTrigger,`,
    `} from "./ui-vendored/dialog";`,
    `export {`,
    `  Select,`,
    `  SelectContent,`,
    `  SelectGroup,`,
    `  SelectItem,`,
    `  SelectLabel,`,
    `  SelectSeparator,`,
    `  SelectTrigger,`,
    `  SelectValue,`,
    `} from "./ui-vendored/select";`,
    `export {`,
    `  AlertDialog,`,
    `  AlertDialogAction,`,
    `  AlertDialogCancel,`,
    `  AlertDialogContent,`,
    `  AlertDialogDescription,`,
    `  AlertDialogFooter,`,
    `  AlertDialogHeader,`,
    `  AlertDialogTitle,`,
    `  AlertDialogTrigger,`,
    `} from "./ui-vendored/alert-dialog";`,
    `export {`,
    `  ContextMenu,`,
    `  ContextMenuContent,`,
    `  ContextMenuItem,`,
    `  ContextMenuSeparator,`,
    `  ContextMenuTrigger,`,
    `} from "./ui-vendored/context-menu";`,
    `export {`,
    `  Popover,`,
    `  PopoverContent,`,
    `  PopoverTrigger,`,
    `} from "./ui-vendored/popover";`,
    ``,
  ].join("\n");
  writeFileSync(join(SDK_ROOT, "src", "ui-bundle.ts"), barrel);

  console.log(
    `vendor-ui: wrote ${PRIMITIVES.length} primitives + barrel into src/ui-vendored/`,
  );
}

main();
